[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "streamlit-shadcn-ui"
version = "1.1.0"
readme = "README.md"
keywords = ["streamlit", "shadcn", "ui", "components"]
description = "Using shadcn components in Streamlit"
authors = [{ name = "Observed Observer", email = "ooer@kanaries.net" }]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]
dependencies = [
    "streamlit>=1.60",
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
homepage = "https://github.com/ObservedObserver/streamlit-shadcn-ui"
repository = "https://github.com/ObservedObserver/streamlit-shadcn-ui"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["streamlit_shadcn_ui*"]
namespaces = false

[tool.setuptools.package-data]
streamlit_shadcn_ui = [
    "pyproject.toml",
    "frontend_v2/dist/**/*",
]
