"""Explicit compatibility namespace for the legacy iframe implementation.

The package root continues to expose this catalog.  This namespace gives
applications a stable rollback import before any future default cutover.
"""

from ..py_components import (
    accordion,
    alert,
    alert_dialog,
    aspect_ratio,
    avatar,
    badges,
    breadcrumb,
    button,
    calendar,
    card,
    checkbox,
    collapsible,
    date_picker,
    dropdown_menu,
    element,
    hover_card,
    input,
    input_otp,
    link_button,
    metric_card,
    pagination,
    popover,
    progress,
    radio_group,
    scroll_area,
    select,
    slider,
    switch,
    table,
    tabs,
    textarea,
    toggle,
    toggle_group,
)

__all__ = [
    "accordion",
    "alert",
    "alert_dialog",
    "aspect_ratio",
    "avatar",
    "badges",
    "breadcrumb",
    "button",
    "calendar",
    "card",
    "checkbox",
    "collapsible",
    "date_picker",
    "dropdown_menu",
    "element",
    "hover_card",
    "input",
    "input_otp",
    "link_button",
    "metric_card",
    "pagination",
    "popover",
    "progress",
    "radio_group",
    "scroll_area",
    "select",
    "slider",
    "switch",
    "table",
    "tabs",
    "textarea",
    "toggle",
    "toggle_group",
]
